### PR TITLE
[T-211]: Cookie provider + Cookie disclaimer

### PR DESCRIPTION
**Pull request by michalpulpan**
Implemented cookie provider (to set & parse cookie of cookie preferences 😄 ) and cookie disclaimer (modal that is shown to user with no cookie preferences 😊 ).
See demo and the cookie itself - if it's readable 😃 .

This PR actually implement #211  and #210 (but #210 wasn't created and I made it as one task - it was easier for debugging 😊 )

https://github.com/ecoseller/ecoseller/assets/34132752/e67e0bcd-c540-45c5-af3f-745064792220

### CODE REVIEW

**Comment by VL-CZ** [comment]
A lot of CSS, I see 😄 
I'm actually surprised there isn't any MUI component for this

otherwise great job btw. 🙂

**Review by VL-CZ — APPROVED** [review]

**Comment by lakatop** [comment]
Would it make sense to remember selected cookies setting for logged in users? So that it doesn't pop-up for them once they select their configuration.

**Comment by michalpulpan** [comment]
> Would it make sense to remember selected cookies setting for logged in users? So that it doesn't pop-up for them once they select their configuration.

Don't add more complexity 😀

**Comment by michalpulpan** [comment]
> otherwise great job btw. 🙂

Thank you!

> A lot of CSS, I see 😄 I'm actually surprised there isn't any MUI component for this


Oh yes, not many libraries implement this by default and I can imagine it'd be premium feature. + they maybe don't want to be legally responsible for some data leakage. But YOLO.

**Review by lakatop — APPROVED** [review]

**Pull request merged**
