### PR TITLE
#T-202: Storefront product API

### PR DESCRIPTION
**Pull request by michalpulpan**
👋 

created some minimal storefront API for fetching products 😊.
It should contain everything we need to render product page

## Updated example with breadcrumbs 🍞 🥖  + media 📷 
http://localhost:8000/product/storefront/1/?pricelist=CZK_maloobchod

```json
{
    "id": 1,
    "breadcrumbs": [
        {
            "id": 1,
            "title": "Káva",
            "slug": "kava"
        },
        {
            "id": 2,
            "title": "zrnková káva",
            "slug": "zrnkova-kava"
        }
    ],
    "title": "Top Spot Espresso",
    "meta_title": "",
    "meta_description": "",
    "short_description": "",
    "description": "",
    "description_editorjs": "",
    "slug": "top-spot-espresso",
    "product_variants": [
        {
            "sku": "espresso250",
            "ean": "",
            "weight": "350.00",
            "price": "250 Kč",
            "attributes": [
                {
                    "id": 1,
                    "order": null,
                    "value": "250",
                    "type": {
                        "id": 1,
                        "type_name": "Weight",
                        "unit": "g"
                    }
                }
            ]
        },
        {
            "sku": "espresso500",
            "ean": "",
            "weight": "0.00",
            "price": "500 Kč",
            "attributes": [
                {
                    "id": 2,
                    "order": null,
                    "value": "500",
                    "type": {
                        "id": 1,
                        "type_name": "Weight",
                        "unit": "g"
                    }
                }
            ]
        }
    ],
    "media": [
        {
            "id": 9,
            "media": "http://localhost:8000/media/product_media/1/image/172-1_espresso1.jpg",
            "type": "IMAGE",
            "alt": null
        },
        {
            "id": 8,
            "media": "http://localhost:8000/media/product_media/1/image/172_top-spot-espresso_IzSaqyC.jpg",
            "type": "IMAGE",
            "alt": null
        },
        {
            "id": 10,
            "media": "http://localhost:8000/media/product_media/1/image/172-4_espresso6.jpg",
            "type": "IMAGE",
            "alt": null
        }
    ]
}
```

### CODE REVIEW

**Comment by michalpulpan** [comment]
ohh god damn, I forgot to add breadcrumbs into the response 😅

**Comment by VL-CZ** [comment]
Looks good 👍🏻 

btw. I don't think we need `published` field. 
The same goes for `category` (maybe we just need its id, slug and title) ?

**Comment by michalpulpan** [comment]
> Looks good 👍🏻
> 
> btw. I don't think we need `published` field. The same goes for `category` (maybe we just need its id, slug and title) ?

You're right, thanks! I reworked serializers to return category (just as breadcrumbs (id, title, slug) 😊) Check example above, pls

**Comment by michalpulpan** [comment]
lol, added `media` field into response. I forgot that too.

**Review by lakatop — APPROVED** [review]

**Pull request merged**
