### PR TITLE
T-38 Cart page - basic layout

### PR DESCRIPTION
**Pull request by VL-CZ**
Hi guys, 
just finished my night shift, so here's the result 😏 

https://github.com/ecoseller/ecoseller/assets/30175078/09de2488-97cb-4b01-b6fd-ab29b79f245c

- cart token is selected from cookie using `useCart()`
- The displayed cart item name is actually name of the product + list of all baseattributes and values of the selected variant

Also note that I updated CartContext a little bit.

### CODE REVIEW

**Comment by michalpulpan** [comment]
Wow! Very nice!! Thanks! 

Just one very quick "UX" note - can you please swtich "+" and "-"  buttons when changing the qty? 😅 (See this please)[https://ux.stackexchange.com/questions/101753/which-goes-on-the-right-plus-or-minus-in-a-counter-feature] - it's defenitelly not a rule, but it feels weird to me to have "increase" on the left 😊 .

And maybe swapping product image with product photo? That's just a nitpicking, but I think it would look a bit cleaner, what do you think?

**Comment by VL-CZ** [comment]
> Just one very quick "UX" note - can you please swtich "+" and "-" buttons when changing the qty? 😅 [See this please](https://ux.stackexchange.com/questions/101753/which-goes-on-the-right-plus-or-minus-in-a-counter-feature) - it's defenitelly not a rule, but it feels weird to me to have "increase" on the left 😊 .

That's a good point, I'll update it

> And maybe swapping product image with product photo? That's just a nitpicking, but I think it would look a bit cleaner, what do you think?

@michalpulpan btw. what is the difference between product image and photo? 
(Currently, I'm getting the photo using `product.get_primary_photo()` method)

**Comment by michalpulpan** [comment]
>  btw. what is the difference between product image and photo?

ummm, it's the same thing I guess 😂. Sorry for confusion

**Review by michalpulpan — APPROVED** [review]

**Comment by lakatop** [comment]
Perfection
image

**Review by lakatop — APPROVED** [review]

**Pull request merged**
