### PR TITLE
[T-170] Permission context provider

### PR DESCRIPTION
**Pull request by lakatop**
Functionality implemented:
 * Permission context provider

Demo with dummy data example - wont be merged:

https://user-images.githubusercontent.com/61156764/235183514-1e3902a6-4c2d-4360-9e7f-c6e9e327a5f9.mov

### CODE REVIEW

**Comment by michalpulpan** [comment]
Wow! 🔥🔥🔥🔥

**Comment by michalpulpan** [comment]
Could you please try to integrate `useUser()` hook into permissions provider? Since it'll be always lover in DOM such as

```typescript
<UserProvider>
   <layout...>
      <someElement>
          <PermissionsProvider permission="product-edit"> 
                <SomeFields/>
          </PermissionsProvider>
      </someElement>
   </layout...>
</UserProvide>
```

btw. can you create list of all possible permissions into a TypeScript type so that `IPermissionProviderProps` wouldn't expect `permission` to be a string but something like `TPermission`? If it makes sense? 
On the other hand it'd be a 💩 -ton of possibilities. What does @VL-CZ think?

**Comment by lakatop** [comment]
> Could you please try to integrate `useUser()` hook into permissions provider? Since it'll be always lover in DOM such as
> 
> ```ts
> <UserProvider>
>    <layout...>
>       <someElement>
>           <PermissionsProvider permission="product-edit"> 
>                 <SomeFields/>
>           </PermissionsProvider>
>       </someElement>
>    </layout...>
> </UserProvide>
> ```
> 
> btw. can you create list of all possible permissions into a TypeScript type so that `IPermissionProviderProps` wouldn't expect `permission` to be a string but something like `TPermission`? If it makes sense? On the other hand it'd be a 💩 -ton of possibilities. What does @VL-CZ think?

Reworked permission provider to use user provider. 
`TPermission` would be nice thing to have, but I dont know if we should do it now, since we dont even have proper permissions in roles defined. Could be done in another issue that would actually incorporate whole permission provider.

**Comment by michalpulpan** [comment]
> TPermission would be nice thing to have, but I dont know if we should do it now, since we dont even have proper permissions in roles defined. Could be done in another issue that would actually incorporate whole permission provider.

Yeah, "nice to have" 😄

**Comment by lakatop** [comment]
> > TPermission would be nice thing to have, but I dont know if we should do it now, since we dont even have proper permissions in roles defined. Could be done in another issue that would actually incorporate whole permission provider.
> 
> Yeah, "nice to have" 😄

I mean, not necessarily 😄 I would be certainly for adding some kind of type check for permissions that will be passed to permission provider. But I think it may require more robust design than just one big enum, and therefore implement it in another task. I've created [dedicated issue](https://github.com/ecoseller/ecoseller/issues/190) for this.

**Review by michalpulpan — APPROVED** [review]
Nice 🙏

**Review by VL-CZ — APPROVED** [review]

**Pull request merged**
