### PR TITLE
[T-43] Order recap

### PR DESCRIPTION
**Pull request by VL-CZ**
# Order recap added

https://github.com/ecoseller/ecoseller/assets/30175078/f203d87e-95dc-4391-b36a-9796674471bc

Added order summary page displaying
- cart items
- billing & shipping address
- shipping & payment method
(note that all values are read-only)

There's also `Complete order` button, which we're going to use for creating orders. Currently, it just redirects user to another page.

Also added progress bar & `prev` & `next` button for all cart steps

@michalpulpan , @lakatop 
Do you guys know, if we have any task for order creation? It should be relatively straightforward (create order, new empty cart for the user,...). We'll also need to integrate our Payment API somehow.

### CODE REVIEW

**Review by michalpulpan — APPROVED** [review]
Good job 😊

**Comment by VL-CZ** [comment]
> Omg, I forgot one quite important thing, sorry. Can you please also implement two checkboxes where one is required to submit the order?

That's a good point.

> I think the workflow for backend could be:
> ...

On the backend, we'll also IMO need some kind of validation (check that products are published and available)

**Comment by michalpulpan** [comment]
> Checkboxes added, see the updated video 🙃

Lovely, good job! Will we move the backend order submission to different issue?

**Review by michalpulpan — APPROVED** [review]

**Comment by michalpulpan** [comment]
> > > Checkboxes added, see the updated video 🙃
> > 
> > 
> > Lovely, good job! Will we move the backend order submission to different issue?
> 
> @michalpulpan Yep, see #284

Nice! ⚡

**Comment by lakatop** [comment]
Is this suppose to go into master? 🤔 How does it behave when you have merged remote branch into this?

**Comment by VL-CZ** [comment]
> Is this suppose to go into master? 🤔 How does it behave when you have merged remote branch into this?

@lakatop 
Yes, firstly I merged your changes, because I thought I'd need it. However, thenI realised that they're not necessary, so I reverted them (there's a commit reverting that merge), see the changed files, there shouldn't be any of your changes.

**Comment by lakatop** [comment]
>@lakatop
Yes, firstly I merged your changes, because I thought I'd need it. However, then I realised that they're not necessary, so I reverted them (there's a commit reverting that merge), see the changed files, there shouldn't be any of your changes.

Oh I see now... sorry, my bad, I overlooked it. Excelent job btw.

**Review by lakatop — APPROVED** [review]

**Pull request merged**
